import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Puedes elegir los pesos que necesites
  variable: "--font-nunito", // Variable CSS
});

export const metadata: Metadata = {
  title: "Agustín Garone",
  description: "Mi portafolio generated by Next.js",
  icons: {
    icon: "./favicon.ico",
    shortcut: "../public/Icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
